### ISSUE TITLE
Theano support?

### ISSUE THREAD

**Issue by toqitahamid** [allanzelener/YAD2K#1]
Can I run the this model on keras on top of theano backend?

**Comment by allanzelener** [comment]
Yes and no.

If you're using a YOLO_v2 model (`yolo.cfg` and `yolo-voc.cfg`) with a passthrough layer then this depends on `tf.space_to_depth`. This is not in the Keras backend and I don't know if Theano has an equivalent function. I have seen an implementation of this [using Theano here](https://github.com/titu1994/Fully-Connected-DenseNets-Semantic-Segmentation/blob/master/layers.py) and would like to switch to something like that eventually. Ideally, space_to_depth will get incorporated into the Keras backend.

The other supported models like `darknet19` and `tiny-yolo-voc` should work fine.

Also, note that `yolo_head()` which post-processes the CNN outputs is implemented as a Keras backend function and not a layer. `yolo_eval()` which is used for filtering predicted boxes based on score and non-maximum-suppression currently uses `tf.non_max_suppression`. A Theano or pure Python equivalent can be used instead.
