### ISSUE TITLE
yad2k.py doesn't generate anchors.txt file

### ISSUE THREAD

**Issue by nanfly** [allanzelener/YAD2K#11]
The following code doesn't work

```python
    if 'region' in cfg_parser.sections():
    #    print('generating anchors file')
        with open('{}_anchors.txt'.format(output_root), 'w') as f:
            print(anchors, file=f)
```

**Comment by allanzelener** [comment]
Ah, good catch. It's because I mangle the section names to parse the cfg with configparser.

I've fixed it now so that it will write the anchors.txt during the main for loop going through each section.

**Comment by nanfly** [comment]
thank you:)

**Comment by abduallahadel** [comment]
I'm facing the same issue

**Comment by ryusaeba** [comment]
me too

**Comment by michaeldong** [comment]
this issue be fixed?  i facing it right now.
