### ISSUE TITLE
Re-train model on new dataset: bbox necessary ?

### ISSUE THREAD

**Issue by MatthiasRMS** [allanzelener/YAD2K#12]
Hi !

I'm working on retraining this model on a new dataset to extract attributes from clothes (e.g sleeves type, neck type etc).

I have a set with images and for each image the attributes, but I don't have the bound boxes of each attribute on the image as it is in the PASCAL VOC dataset.

Do I need the bound boxes to retrain it ?

**Comment by allanzelener** [comment]
Yes, for a YOLO style model you need bounding box ground truth data.

If you don't have bounding boxes I recommend looking at this paper: http://cnnlocalization.csail.mit.edu/
It describes how to make a CNN that generates a class activation map from just image level labels.
