### ISSUE TITLE
Quick start problem on cfg file download.

### ISSUE THREAD

**Issue by Sangkwun** [allanzelener/YAD2K#132]
It's 404 not found for cfg file in quick start.
https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/yolo.cfg
Above url is not avialable now..
Could you give me another url for cfg file?

**Comment by ghost** [comment]
The one you need might be https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/yolov2.cfg now.

**Comment by streamB** [comment]
In that case, should we download the corresponding weights(yolov2) as :
  $ wget http://pjreddie.com/media/files/yolov2.weights
instead of the following link ??
  $ wget http://pjreddie.com/media/files/yolo.weights

**Comment by Sangkwun** [comment]
Thanks for giving other options!
