### ISSUE TITLE
Include h5py as a dependency

### ISSUE THREAD

**Issue by PavlosMelissinos** [allanzelener/YAD2K#14]
Hi,

h5py is necessary to run this command:

`./yad2k.py cfg/yolo.cfg yolo.weights model_data/yolo.h5`

and miniconda does not include the package by default.

However, `conda install h5py` works like a charm, so please consider adding the dependency to the README or environment.yml

Thank you for the project!

**Comment by allanzelener** [comment]
h5py is a dependency for Keras, but yes the environment.yml currently seems incomplete and probably should be updated. It's tricky because usually it seems better to install Keras from pip to get the latest version.

**Comment by PavlosMelissinos** [comment]
I see... I wouldn't really say environment.yml is incomplete but you know better! However, even though I did install keras from pip, I still had to install h5py manually. This is the output of pip show for keras on my system:

```
$ pip show keras
Name: Keras
Version: 2.0.2
Summary: Deep Learning for Python
Home-page: https://github.com/fchollet/keras
Author: Francois Chollet
Author-email: francois.chollet@gmail.com
License: MIT
Location: ~/miniconda2/envs/yad2k/lib/python3.6/site-packages
Requires: theano, six, pyyaml
```

Apparently h5py is an optional dependency for keras (pip install keras doesn't seem to include it) but since it's part of the conversion in yad2k, maybe it should be noted here as well? After all, you mention numpy under the requirements section and that's a keras dependency as well.

Anyway, I'm nitpicking really. I'm inclined to keep this issue open as a reminder, since you admitted the requirements file should be updated, but of course you may close it if you think it is or becomes irrelevant.

I'll be using your project heavily during the next few weeks, so thanks again!

**Comment by allanzelener** [comment]
I've updated the environment.yml to include the dependencies necessary to run each script and mention the major ones in the README.md. Conda now also seems to track the versions of packages installed through pip which is nice and makes it a true replacement for a requirements.txt.
