### ISSUE TITLE
iou compute

### ISSUE THREAD

**Issue by tsminhuang** [allanzelener/YAD2K#17]
in preprocess_true_boxes  
compute box area  `box_area = box[2] * box[3]`
but the box is relative value to original 
To compute box area on final conv dim need multiply with conv_dim?
`box_area  = (box[2] *conv_width) * (box[3] * conv_height)`

**Comment by allanzelener** [comment]
Ah, you're right! Thanks for catching that! I'll patch and test it later today. 

Btw this box scale issue has been the biggest headache implementing this loss function. Adding the rescaling to the correct scale on line 401 (`box_maxes = box[2:4] * np.array([conv_width, conv_height]) / 2.`) to compute the intersection area is what finally got it working on `train_overfit.py` but the union area is definitely still strong. There's three different ways bounding box scales are represented (image scale, [0,1] interval, final conv scale) and at least three different ways to define/order the bounding box coordinates. :cry:

**Comment by allanzelener** [comment]
I've fixed this and refactored how ground truth box scaling works in `preprocess_true_boxes` in [https://github.com/allanzelener/YAD2K/commit/a2c5dc9b9a9ab520074433a36af53e4bb9f25c84#diff-e3ae7ac93e96dbaeb2761c2f9007fcf3](this commit).
