### ISSUE TITLE
"Mismatch between model and given anchor and class sizes" for tiny YOLO 

### ISSUE THREAD

**Issue by xslittlegrass** [allanzelener/YAD2K#2]
I'm having a problem testing with the tiny YOLO:

```
./yad2k.py cfg/tiny-yolo-voc.cfg tiny-yolo-voc.weights model_data/tiny-yolo-voc.h5
./test_yolo.py model_data/tiny-yolo-voc.h5
```

Are the postprocessings different for the yolo and tiny yolo? Could you have a look? Thanks very much for your sharing of this project, it's very helpful!

**Comment by allanzelener** [comment]
If you're using one of the models that isn't trained on the COCO dataset then you have to use the `--classes_path`  path flag to specify the classes the model is trained on. You can find the list of PASCAL VOC classes in `model_data/pascal_classes.txt`.

Also if you're using any model other than `yolo.cfg` then you need to give the `--anchors_path` to specify the anchor boxes the model was trained with. These are saved separately when you run `yad2k.py`, e.g. as `model_data/tiny-yolo-voc_anchors.txt`.

In the future I may try to get these saved as part of the model file itself. For now I've expanded the error message to inform the user about these flags.

(Also note that tiny-yolo-voc is a small model with poor performance so it will make mistakes on the included test images.)

**Comment by xslittlegrass** [comment]
Thanks for the reply. It works by adding the path, but I get another error:

`./test_yolo.py model_data/tiny-yolo-voc.h5 --classes_path model_data/pascal_classes.txt --anchors_path model_data/tiny-yolo-voc_anchors.txt`

```
model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
model_data/tiny-yolo-voc.h5 model, anchors, and classes loaded.
Traceback (most recent call last):
  File "./test_yolo.py", line 186, in <module>
    _main(parser.parse_args())
  File "./test_yolo.py", line 107, in _main
    yolo_outputs = yolo_head(yolo_model.output, anchors, len(class_names))
  File "/Users/xslittlegrass/Deep_learning/YAD2K/yad2k/models/keras_yolo.py", line 100, in yolo_head
    conv_height_index = K.arange(0, stop=conv_dims[0])
AttributeError: module 'keras.backend' has no attribute 'arange'
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x12a0bd898>>
Traceback (most recent call last):
  File "/Users/xslittlegrass/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 581, in __del__
AttributeError: 'NoneType' object has no attribute 'TF_DeleteStatus' 
```

Do you have any ideas? Thanks.

**Comment by xslittlegrass** [comment]
This problem is solved by upgrading keras.

**Comment by yquemener** [comment]
If you have to use different classes than the default ones, the current script will ignore the `--classes` argument, leading to this error. There is a fix in this pull request https://github.com/qqwweee/keras-yolo3/pull/301

You will need to use `--classes_path` instead of `--classes` and it should work.
