### ISSUE TITLE
Prediction time

### ISSUE THREAD

**Issue by titoghose** [allanzelener/YAD2K#23]
I tested the prediction time without visualization for your model using the test_yolo code by subtracting time before and after 'sess.run' : 
[https://github.com/allanzelener/YAD2K/blob/master/test_yolo.py#L142](url)
and it comes out to be around 1350 ms. Am I going wrong in this caluculation somewhere or is this the time it takes?
Because according to the paper, the model should give around 50 fps.
Thankyou.

**Comment by allanzelener** [comment]
I haven't done benchmarks for this myself but there are many possible reasons for performance differences.

- The reported FPS may only be measuring the latency from start to end of running the model on the GPU. It may not include the time to retrieve the result into memory of the Python script running the model with may dominate the time of a sess.run() call.
- There may be optimization differences between the Darknet implementation of operations and the Tensorflow/Theano implementations. When using Tensorflow check the performance guidelines here: https://www.tensorflow.org/performance/
- There may be differences based on your hardware. In the YOLO_v2 paper they report using a Titan X Maxwell GPU. 
- There may be an issue with calling sess.run() from a cold start. You may get better average performance if you discard the first few times the model is run by a test script. The test_yolo script just runs once for each provided test image and only for a small number of images. 
- I don't think it's the case here but it's possible for throughput (FPS) to be higher than latency (seconds per frame) if you can pipeline multiple frames on the GPU. But I'm not aware if anyone does this or if it's even possible. The reported FPS in the YOLO_v1 paper is just 1 / reported latency.

**Comment by titoghose** [comment]
Ohk thankyou
ill try out what you said
