### ISSUE TITLE
unicode argument expected, got 'str'

### ISSUE THREAD

**Issue by yanmenglu** [allanzelener/YAD2K#29]
@allanzelener hello，when I run  ./yad2k.py   yolo.cfg   yolo.weights   model_data/yolo.h5  
It takes error. like this:

section-counters defaultdict(<type 'int'>, {})
Traceback (most recent call last):
  File "yad2k.py", line 269, in <module>
    _main(parser.parse_args())
  File "yad2k.py", line 89, in _main
    unique_config_file = unique_config_sections(config_path)
  File "yad2k.py", line 60, in unique_config_sections
    output_stream.write(line)
TypeError: unicode argument expected, got 'str'

How could I resolve it ？thank you .

**Comment by allanzelener** [comment]
Haven't seen that error before. Are you using Python 2 or 3? One of the big differences is the changes to strings, byte strings, and unicode strings.

**Comment by yanmenglu** [comment]
@allanzelener ,Thank you ,when I use  Python 3, the error is solved.

**Comment by satiyam** [comment]
Got the same issue. How do I resolve it on Python2?

**Comment by alecGraves** [comment]
you can convert the model with python3 then train/run/whatever in python2 if you need to. Maybe check out one of the PRs that claims to extend to py2 support.
