### ISSUE TITLE
Question about the post-processing steps

### ISSUE THREAD

**Issue by xslittlegrass** [allanzelener/YAD2K#3]
@allanzelener In your implementation, you seem to have taken the output from the Keras model and do the post processing steps in tensorflow. I'm wondering what prevent you from using the 100% keras in the implementation, and why you need tensorflow in the postprocessing steps? 

In the [darkflow](https://github.com/thtrieu/darkflow) implementation, the post-processing steps are in pure python and completely decoupled from the model evaluation steps (for example, the post-processing steps are all in `darkflow/net/yolov2/test.py`). 

I tried to take the Keras model in your implementation and feed into the post-processing steps in the darkflow implementation, and the class of the object is detected correctly, but the bounding box seems slightly off. I'm wondering whether you have any ideas/suggestions about this problem. Here is the detail of my experiment:

I first convert the darknet model into Keras model:

`./yad2k.py cfg/tiny-yolo-voc.cfg tiny-yolo-voc.weights model_data/tiny-yolo-voc.h5`

Then load the model into Keras and evaluate on an image:

```
image = Image.open('./images/eagle.jpg')
resized_image = image.resize((416,416), Image.BICUBIC)
image_data = np.array(resized_image, dtype='float32')
image_data /= 255.
image_data = np.expand_dims(image_data, 0)  # Add batch dimension.

model = load_model('./model_data/tiny-yolo-voc.h5')
net_out = (model.predict(image_data))[0]
```

I then feed the output from the network into the darknet post-processing steps:

```
plt.figure(figsize = (20,6))
plt.imshow(postprocess(net_out,plt.imread(image_path)))
```

And [here](http://i.imgur.com/Hnty9mw.jpg) is the result, we can see that the box is slightly off.

---

Here are the postprocess code:

```
class BoundBox:
    def __init__(self, classes):
        self.x, self.y = float(), float()
        self.w, self.h = float(), float()
        self.c = float()
        self.class_num = classes
        self.probs = np.zeros((classes,))

def overlap(x1,w1,x2,w2):
    l1 = x1 - w1 / 2.;
    l2 = x2 - w2 / 2.;
    left = max(l1, l2)
    r1 = x1 + w1 / 2.;
    r2 = x2 + w2 / 2.;
    right = min(r1, r2)
    return right - left;

def box_intersection(a, b):
    w = overlap(a.x, a.w, b.x, b.w);
    h = overlap(a.y, a.h, b.y, b.h);
    if w < 0 or h < 0: return 0;
    area = w * h;
    return area;

def box_union(a, b):
    i = box_intersection(a, b);
    u = a.w * a.h + b.w * b.h - i;
    return u;

def box_iou(a, b):
    return box_intersection(a, b) / box_union(a, b);

def prob_compare(box):
    return box.probs[box.class_num]

def prob_compare2(boxa, boxb):
    if (boxa.pi < boxb.pi):
        return 1
    elif(boxa.pi == boxb.pi):
        return 0
    else:
        return -1

def expit(x):
	return 1. / (1. + np.exp(-x))

def _softmax(x):
    e_x = np.exp(x - np.max(x))
    out = e_x / e_x.sum()
    return out

def postprocess(net_out, im, save = True):
	"""
	Takes net output, draw net_out, save to disk
	"""
	# meta
	H, W, _ = [13, 13, 125]
	threshold = 0.2
	C, B = 20, 5
	anchors = [1.08, 1.19, 3.42, 4.41, 6.63, 11.38, 9.42, 5.11, 16.62, 10.52]
	net_out = net_out.reshape([H, W, B, -1])

	boxes = list()
	for row in range(H):
		for col in range(W):
			for b in range(B):
				bx = BoundBox(C)
				bx.x, bx.y, bx.w, bx.h, bx.c = net_out[row, col, b, :5]
				bx.c = expit(bx.c)
				bx.x = (col + expit(bx.x)) / W
				bx.y = (row + expit(bx.y)) / H
				bx.w = math.exp(bx.w) * anchors[2 * b + 0] / W
				bx.h = math.exp(bx.h) * anchors[2 * b + 1] / H
				classes = net_out[row, col, b, 5:]
				bx.probs = _softmax(classes) * bx.c
				bx.probs *= bx.probs > threshold
				boxes.append(bx)

	# non max suppress boxes
	for c in range(C):
		for i in range(len(boxes)):
			boxes[i].class_num = c
		boxes = sorted(boxes, key = prob_compare)
		for i in range(len(boxes)):
			boxi = boxes[i]
			if boxi.probs[c] == 0: continue
			for j in range(i + 1, len(boxes)):
				boxj = boxes[j]
				if box_iou(boxi, boxj) >= .4:
					boxes[j].probs[c] = 0.


	colors = [(254.0, 254.0, 254), (239.88888888888889, 211.66666666666669, 127), 
              (225.77777777777777, 169.33333333333334, 0), (211.66666666666669, 127.0, 254),
              (197.55555555555557, 84.66666666666667, 127), (183.44444444444443, 42.33333333333332, 0),
              (169.33333333333334, 0.0, 254), (155.22222222222223, -42.33333333333335, 127),
              (141.11111111111111, -84.66666666666664, 0), (127.0, 254.0, 254), 
              (112.88888888888889, 211.66666666666669, 127), (98.77777777777777, 169.33333333333334, 0),
              (84.66666666666667, 127.0, 254), (70.55555555555556, 84.66666666666667, 127),
              (56.44444444444444, 42.33333333333332, 0), (42.33333333333332, 0.0, 254), 
              (28.222222222222236, -42.33333333333335, 127), (14.111111111111118, -84.66666666666664, 0),
              (0.0, 254.0, 254), (-14.111111111111118, 211.66666666666669, 127)]
	labels = ['aeroplane', 'bicycle', 'bird', 'boat', 'bottle', 
              'bus', 'car', 'cat', 'chair', 'cow', 'diningtable', 
              'dog', 'horse', 'motorbike', 'person', 'pottedplant',
              'sheep', 'sofa', 'train', 'tvmonitor']
	if type(im) is not np.ndarray:
		imgcv = cv2.imread(im)
	else: imgcv = im
	h, w, _ = imgcv.shape
	for b in boxes:
		max_indx = np.argmax(b.probs)
		max_prob = b.probs[max_indx]
		label = 'object' * int(C < 2)
		label += labels[max_indx] * int(C>1)
		if max_prob > threshold:
			left  = int ((b.x - b.w/2.) * w)
			right = int ((b.x + b.w/2.) * w)
			top   = int ((b.y - b.h/2.) * h)
			bot   = int ((b.y + b.h/2.) * h)
			if left  < 0    :  left = 0
			if right > w - 1: right = w - 1
			if top   < 0    :   top = 0
			if bot   > h - 1:   bot = h - 1
			thick = int((h+w)/300)
			cv2.rectangle(imgcv, 
				(left, top), (right, bot), 
				colors[max_indx], thick)
			mess = '{}'.format(label)
			cv2.putText(imgcv, mess, (left, top - 12), 
				0, 1e-3 * h, colors[max_indx],thick//3)

	return imgcv
```

**Comment by allanzelener** [comment]
I've looked into this a bit but can't find any obvious errors, it looks like this should work. Can you post a few more examples? I'll just try to answer your questions for now.

Post-processing is implemented in Tensorflow mostly because I wanted to use `tf.image.non_max_suppression`. Also the training function will need to be implemented using similar tensor manipulations.

Also could you try resizing the output image to 416x416 and see if the box appears correctly there? It looks like the issue might be with translating the relative box coordinates to absolute image coordinates.

**Comment by xslittlegrass** [comment]
I was also thinking about the image dimension, but it seems to still have the same problem even using resized image:

```
image = Image.open('./images/eagle.jpg')
resized_image = image.resize((416,416), Image.BICUBIC)
image_data = np.array(resized_image, dtype='float32')
image_data /= 255.
image_data = np.expand_dims(image_data, 0)  # Add batch dimension.

model = load_model('./model_data/tiny-yolo-voc.h5')
net_out = (model.predict(image_data))[0]

plt.figure(figsize = (20,6))
plt.imshow(postprocess(net_out,np.array(resized_image)))
```

And the result is [here](http://imgur.com/a/XzqHI)

**Comment by allanzelener** [comment]
Okay, I checked this out a bit and the differences seem to mostly be due to the thresholds used for the non-maximum suppression and probably the implementation of NMS itself. If you set the probability threshold to 0.6 (which is in the tiny-yolo-voc.cfg under the [regions] section) then you'll get better results. Also if you increase the IOU threshold for NMS then you'll see if a bad box is killing a better box. 

I still get slightly different boxes between Darkflow, Yad2k, and Yad2k + Darkflow postprocessing but they're all roughly similar and not different in ways that can be explained by a simple bug of transforming coordinates.

One other difference I noticed is that the Darkflow postprocessing considers every possible class for each box whereas I only consider the score for the highest scoring class. I don't think this should make a difference in practice, however this is more like the Darknet implementation for NMS.

**Comment by xslittlegrass** [comment]
Thanks. Change the threshold seems to solve the problem. Did you compare the network output before postprocessing between the original yolo, Darkflow and Yad2k? In theory they should all be the same, right?

**Comment by allanzelener** [comment]
I did some comparison between Darkflow and Yad2k when I was debugging my implementation, I think they do give the same network outputs within a small tolerance for floating point error. I haven't tried comparing with the original Darknet but it should also be the same, although it does use a different low-level implementation for all the operations. My main goal here was to implement YOLO_v2 using higher-level Keras operations (and Tensorflow when necessary) so I'm not too concerned with exact replication.

**Comment by xslittlegrass** [comment]
Thank you very much for all your help. I'm closing this issue now.
