### ISSUE TITLE
missing 1 required positional argument: 'nb_col'

### ISSUE THREAD

**Issue by yanmenglu** [allanzelener/YAD2K#30]
@allanzelener ,when I run like this,but mat that error.It maybe is the keras ,I use keras1.1.1.

yad2k.py   yolo.cfg   yolo.weights  model_data/yolo.h5
Using TensorFlow backend.
Loading weights.
Weights Header:  [      0       1       0 5133312]
Parsing Darknet config.
section-counters defaultdict(<class 'int'>, {})
Creating Keras model.
Parsing section net_0
Parsing section convolutional_0
conv2d bn leaky (3, 3, 3, 32)
Traceback (most recent call last):
  File "yad2k.py", line 269, in <module>
    _main(parser.parse_args())
  File "yad2k.py", line 186, in _main
    padding=padding))(prev_layer)
TypeError: __init__() missing 1 required positional argument: 'nb_col'

**Comment by yanmenglu** [comment]
@allanzelener ,Now I uesd the Anaconda python envrionment, and conda update -n python34 keras,the newest keras is keras 1.1.1.

**Comment by allanzelener** [comment]
The code here has been updated to the Keras 2 API which is not backwards compatible with Keras 1. When I do `conda search keras` I see the latest as 2.0.2 for Python 3.5+. Note that this is a few version behind the keras pip distribution (2.0.4) so I'd recommend using pip to install keras.
