### ISSUE TITLE
model_data/yolo_anchors.txt is disappear

### ISSUE THREAD

**Issue by ryusaeba** [allanzelener/YAD2K#35]
Firstly, thanks for your great work. 
I have already converted the model to keras version (model_data/yolo.h5). 
Then I would like to run "./test_yolo.py model_data/yolo.h" but it said that No such file or directory: 'model_data/yolo_anchors.txt'.
I search your repository but still can't find the txt file. 
Anything I miss please point me out. Thanks!

**Comment by allanzelener** [comment]
That file should be generated when `yad2k.py` is parsing `yolo.cfg` at this line: https://github.com/allanzelener/YAD2K/blob/master/yad2k.py#L240

Make sure that the yolo.cfg you're using has a `[region]` section with an `anchors` field.

**Comment by ryusaeba** [comment]
Thanks for the kindly reply :) I guess maybe the problem is because of different python version. Anyway, it works well after using your suggestion (manually copying the values into a new files). Thanks again
