### ISSUE TITLE
Convert .h5 to .weights

### ISSUE THREAD

**Issue by Ahziel** [allanzelener/YAD2K#55]
Hi,

I was wondering how to convert the `.h5` file of Keras to the `.weights` file used by Darknet.  If I undertsand, the `.h5` file created with  YAD2K is the entire model. I find on Keras documentation that you can save only the weight of this model, but the data of this  `.h5` is not the same as the data in the `.weight` file.

What transformations I have to do to convert this file into `.weight` ?

Thank you for your attention and your help!

**Comment by Firyuza** [comment]
[https://github.com/allanzelener/YAD2K/issues/52](url)

**Comment by Firyuza** [comment]
I this issue you can find how to convert .weight to .h5 extension. Just using the yad2k command in terminal.

**Comment by Ahziel** [comment]
Thank's for your answer but, I don't want to convert `.weights` to `.h5` but `.h5` to `.weights`

**Comment by Firyuza** [comment]
Oh, didn't understand clearly. Maybe look into script that convert to .h5 and find the way how to do vice versa.

**Comment by Ahziel** [comment]
The real problem is that I don't know how are organize the information of the `.weights` file and the `.h5` file, what information is in it. Maybe there is an easy way to find this information but I'm kind of a newbie (I'm totally a newbie...) in deep learning and this type of thing. On top of that when I whatch the code I don't understand a lot.

**Comment by Ahziel** [comment]
I solved the problem, I just reversed the process of `yad2k.py`. Now, it worked, thanks for your time !

**Comment by demcoderseinnachbar** [comment]
Would yu mind to share the result?

**Comment by alice17** [comment]
@Ahziel Could you please share the code?

**Comment by Ahziel** [comment]
Hi,

It's been a long time since I've done deep learning and I don't have the YOLO code anymore and I don't remember how was my code. Thus I can't help you with your problems. I hope you'll excuse me, I'm really sorry and I hope you'll succeed in your projects.

With kind regards

**Comment by saivineethkumar** [comment]
Hi @alice17 @demcoderseinnachbar 
Did u guys find the code for converting .h5 to .weight file?
If yes, can u share the code!
thanks

**Comment by shuli163love** [comment]
@saivineethkumar 

Hi. I have the save issue.  If you find a way to convert .h5 to .weihts, please share the code. Thanks!
My email is   lishuli@ruijie.com.cn

**Comment by sevenseablue** [comment]
@shuli163love 
Hi. I have the save issue. If you find a way to convert .h5 to .weihts, can you share me. Thanks!
My email is 178129482@qq.com

**Comment by Caliber2** [comment]
Hey, did anybody find the solution? Sharing the solution would be appreciated.

**Comment by Wintersara** [comment]
Somebody solved it?

**Comment by saminhasan** [comment]
Same issue

**Comment by Kenny-Snub-Nose-Monk** [comment]
Here ~ But Chinese, I think you can translate it by Google~ 
I successfully deal with it by this website
 
https://www.cnblogs.com/shouhuxianjian/p/10567201.html

**Comment by Kenny-Snub-Nose-Monk** [comment]
Here ~ Another solution~
# 3. Convert the Darknet YOLO model to a Keras model:
https://github.com/YuXiuChen/Object-Detection-and-Tracking/blob/master/OneStage/yolo/deep_sort_yolov3/README.md
or 

https://github.com/YuXiuChen/Darknet-yolov3.cfg-and-yolov3.weights-transform-to-keras.h5/blob/master/README.md

**Comment by chandanadittyo** [comment]
@YuXiuChen 
 Does it work for h5 to weight convert??

**Comment by ywj55555** [comment]
> Here ~ Another solution~
> 
> # 3. Convert the Darknet YOLO model to a Keras model:
> https://github.com/YuXiuChen/Object-Detection-and-Tracking/blob/master/OneStage/yolo/deep_sort_yolov3/README.md
> or
> 
> https://github.com/YuXiuChen/Darknet-yolov3.cfg-and-yolov3.weights-transform-to-keras.h5/blob/master/README.md
Hi，I used the second solution you provide,then it occur nameerror that my function is not defined,but I train the model noramlly. is there some bugs in the code?

**Comment by ywj55555** [comment]
> @YuXiuChen
> Does it work for h5 to weight convert??

When I run the second,it occurs nameerror that my function is not defined, but I train the model noramlly,I can't solve the bug. I think this code has some bugs for certain h5 files，it's not common for all h5 files.

**Comment by ywj55555** [comment]
Does anyone have other ways？please

**Comment by SauravRai** [comment]
@YuXiuChen That is just the reverse of what is being asked. The question is to convert .h5 to .weights file and not the other way. Anyone who was able to do it, kindly share the code. I will do the same if I am able to do it. Thanks.
