### ISSUE TITLE
Weights loading time

### ISSUE THREAD

**Issue by linamede** [allanzelener/YAD2K#6]
It takes over 60 seconds to load the h5 file. It is possible to reduce the time needed for this process?
Thank you

**Comment by allanzelener** [comment]
There's no way to speed this up as far as I know, but I don't think it should take that long. 

It only takes me 6-7 seconds to completely run the test_yolo script on an SSD.

**Comment by linamede** [comment]
Something weird happens. When i run the model from a virtual environment, where Keras (1.2.1) is installed, it takes almost 4 sec. to load the model.  However when I run it from the global python environment where  Keras (1.2.2) is installed, it takes almost 1 minute to load. Which Keras version do you use? Can you explain this difference?
Thank you!
