### ISSUE TITLE
test_yolo.py results is quite different from darknet results

### ISSUE THREAD

**Issue by ACfromecs** [allanzelener/YAD2K#75]
I had a model trained by darknet with my own data and want to do in python.
My model is weights by darknet19_448.conv.23 with cfg/yolo.cfg,
and had changed line "buffer=weights_file.read(16)" to "buffer=weights_file.read(20)" in yad2k.py.
When I do test_yolo.py, same image get results that is quite different from do by darknet.
It looks like test_yolo.py get right classes but wrong boxes setting in the image,
and some classes found by darknet are not show in test_yolo.py results.
The classes show in results are true but with wrong boxes, items exist but not in boxes.
Any tips?
Thanks.

**Comment by Firyuza** [comment]
Hi @ACfromecs , try to remove reversed at 156 line and write like this:
for i, c in list(enumerate(out_classes))

**Comment by ACfromecs** [comment]
Thanks for your answer, @Firyuza 
But after I changed the line, my station (jetson TX2) restart every time when I do test_yolo.py

**Comment by Firyuza** [comment]
@ACfromecs I did it and it works correctly.

**Comment by ACfromecs** [comment]
@Firyuza 
I tried "print(list(enumerate(out_classes)))" before "for i, c in reversed(list(enumerate(out_classes))):",
then my system restart again.
It looks like your solution did not work on my system.
Anyway, thanks for your help.

**Comment by Firyuza** [comment]
@ACfromecs Try another way to iterate items within this list out_classes. Maybe list() doesn't work for your system or enumerate.

**Comment by ACfromecs** [comment]
@Firyuza 
Thanks for your help.
I re-download test_yolo.py and remove reversed at 156 line then it worked.
But results still not fixed darknet results.
I then re-download full yad2k file and get the same results (following pic.1) that is different from darknet results (following pic.2)
I have 9 classes in my list and both result show the right 4 classes, but yad2k just boxed at wrong place.
![000644](https://user-images.githubusercontent.com/32084524/31710303-2b136a2e-b427-11e7-8e51-36e67c7360e0.jpg)
![predictions](https://user-images.githubusercontent.com/32084524/31710304-2b856f16-b427-11e7-88f7-2dc56b7aaf9a.jpg)

**Comment by Firyuza** [comment]
@ACfromecs I checked code and didn't find mistakes. But I noticed that loss function is another. But I don't know, maybe darknet implemented the same. But in paper the formula is different. Also you can try to retrain yad2k, now I'm working on it and haven't succeeded yet. At the same time read other issues some people got result.

**Comment by ACfromecs** [comment]
@Firyuza 
Thanks for your advice.
I found out the error is caused by training with yolo.cfg
That worked in darknet but got error here.
Retrain my data with tiny-yolo-voc.cfg solved the error.

**Comment by Firyuza** [comment]
@ACfromecs Cool! What the error did you find?

**Comment by ACfromecs** [comment]
@Firyuza 
Actually I did not find which line caused the error.
I just clear my data and re-train my imageset with tiny-yolo-voc.cfg.
THe origen file is trained with yolo-voc.cfg, I think that is the quastion.
Thanks.
