### ISSUE TITLE
keras 2

### ISSUE THREAD

**Issue by PiSimo** [allanzelener/YAD2K#8]
Hi, does it work with the newest version of keras ? (By the way,you have done a great job)

**Comment by allanzelener** [comment]
I haven't had time to test with Keras 2 but it should be backwards compatible with the Keras 1 API. Eventually I'll convert everything to the Keras 2 API.

**Comment by PiSimo** [comment]
I've upgraded Keras and tensorflow to their latest versions and it's still working perfectly

**Comment by n-log-n** [comment]
@PiSimo Which version of Keras and Tensorflow you are using? I am running into bunch of issues try to convert the Yolov2 model to Keras including a problem with the merge layer.

**Comment by PiSimo** [comment]
Keras version is 2.0.2 while tensorflow is 1.0.0

**Comment by JamesLuoau** [comment]
I upgraded to keras 2.0.2, tensorflow 1.0.0, while convert weights file to h5, I got this error

Parsing section convolutional_20
conv2d bn leaky (3, 3, 3072, 1024)
Traceback (most recent call last):
  File "./yad2k.py", line 274, in <module>
    _main(parser.parse_args())
  File "./yad2k.py", line 155, in _main
    buffer=weights_file.read(weights_size * 4))
TypeError: buffer is too small for requested array

**Comment by JamesLuoau** [comment]
Keras version 2.0.2 while tensorflow 1.0.0 worked very well in my machine, include convert weights to h5

**Comment by allanzelener** [comment]
All API calls have now been updated to the Keras 2 API.
