### ISSUE TITLE
retrain for Tiny yolo

### ISSUE THREAD

**Issue by jayakrishna-a** [allanzelener/YAD2K#90]
I converted tiny-yolo weights to h5 format using yad2k.py script. I also generated training data in .npz format. When I retrain using this tiny yolo weights, I am getting the following error:

File "retrain_yolo.py", line 348, in <module>
    _main(args)
  File "retrain_yolo.py", line 69, in _main
    model_body, model = create_model(anchors, class_names)
  File "retrain_yolo.py", line 205, in create_model
    topless_yolo.load_weights(topless_yolo_path)
  File "/home/jayakrishna/.local/lib/python2.7/site-packages/keras/engine/topology.py", line 2622, in load_weights
    load_weights_from_hdf5_group(f, self.layers)
  File "/home/jayakrishna/.local/lib/python2.7/site-packages/keras/engine/topology.py", line 3116, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 16 layers into a model with 44 layers.

It looks like it is creating a full yolo model. How to create a tiny yolo model in retrain_yolo.py?

**Comment by jayakrishna-a** [comment]
I have added the tiny yolo network in keras_yolo.py. I am able to re-train the tiny yolo now.

**Comment by helloniklas** [comment]
@jayakrishna-a I'm just attempting to do the same, if you have some spare time, do mind outlining the steps to achieve this. And how to create the npz file? I'm currently stuck at this error.

```File "retrain_yolo.py", line 60, in _main
    image_data, boxes = process_data(data['images'], data['boxes'])
  File "retrain_yolo.py", line 125, in process_data
    boxes_xy = [0.5 * (box[:, 3:5] + box[:, 1:3]) for box in boxes]
  File "retrain_yolo.py", line 125, in <listcomp>
    boxes_xy = [0.5 * (box[:, 3:5] + box[:, 1:3]) for box in boxes]
TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U21') dtype('<U21') dtype('<U21')```

**Comment by helloniklas** [comment]
ok got past that by casting as float

**Comment by jayakrishna-a** [comment]
@helloniklas: 
1) Generate a tiny-yolo.h5 using yad2k.py script.
2) Refer tiny-yolo.cfg from the original YOLO darknet and write the corresponding network in a function.
(Use this model in retrain_yolo.py)
3) Create dataset in npz file which you have done already.

Using these steps I could retrain. Please let me know if you have any specific doubts.

**Comment by helloniklas** [comment]
@jayakrishna-a thanks a lot. As it turns out. Apple just released an open source framework that does all I want and which seems very easy to train and then convert to CoreML. Will give that a go. https://github.com/apple/turicreate/blob/master/userguide/object_detection/introduction.md

**Comment by abhaybd** [comment]
@jayakrishna-a I know this is a pretty old thread, but this is the exact problem I'm having. When you say "write the corresponding network in a function", what does that mean? I'm looking at the `tiny-yolo-voc.cfg` file, but I'm pretty unsure how to convert the last half of that into the code similar to what's already there. Could I see your code, and how you solved this?
